[package]
name = "bevy-query-vs-hash-map"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
iyes_perf_ui = "0.3"
rand = "0.8"
rand_chacha = "0.3"
web-time = "1.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[toolchain]
channel = "nightly"
